const codes = { // Currencies Codes to Names
    "usd" : "US Dollar",
    "brl" : "Brazilian Real",
    "eur" : "Euro",
    "jpy" : "Japanese Yen",
    "chf" : "Swiss Franc",
    "cad" : "Canadian Dollar",
    "zar" : "South African Rand",
    "try" : "New Turkish Lira",
    "mxn" : "Mexican Peso",
    "pln" : "Polish Złoty",
    "sek" : "Swedish Krona",
    "sgd" : "Singapore Dollar",
    "dkk" : "Danish Krone",
    "nok" : "Norwegian Krone",
    "ils" : "New Israeli Shekel",
    "huf" : "Hungarian Forint",
    "czk" : "Czech Koruna",
    "thb" : "Thai Baht",
    "aed" : "Emirati Dirham",
    "jod" : "Jordanian Dinar",
    "kwd" : "Kuwaiti Dinar",
    "hkd" : "Hong Kong Dollar",
    "sar" : "Saudi Riyal",
    "inr" : "Indian Rupee",
    "krw" : "South Korean Won",
    "all" : "Albanian Lek",
    "amd" : "Armenian Dram",
    "ang" : "Netherlands Antillean Guilder",
    "ars" : "Argentine Peso",
    "aud" : "Australian Dollar",
    "bbd" : "Barbadian Dollar",
    "bdt" : "Bangladeshi Taka",
    "bgn" : "Bulgarian Lev",
    "bhd" : "Bahraini Dinar",
    "bif" : "Burundian Franc",
    "bnd" : "Brunei Dollar",
    "bob" : "Bolivian Boliviano",
    "bsd" : "Bahamian Dollar",
    "bwp" : "Botswana Pula",
    "bzd" : "Belize Dollar",
    "clp" : "Chilean Peso",
    "cny" : "Chinese Yuan",
    "cop" : "Colombian Peso",
    "crc" : "Costa Rican Colón",
    "cup" : "Cuban Peso",
    "djf" : "Djiboutian Franc",
    "dop" : "Dominican Peso",
    "dzd" : "Algerian Dinar",
    "egp" : "Egyptian Pound",
    "etb" : "Ethiopian Birr",
    "fjd" : "Fijian Dollar",
    "gbp" : "British Pound",
    "gel" : "Georgian Lari",
    "ghs" : "Ghanaian Cedi",
    "gmd" : "Gambian Dalasi",
    "gnf" : "Guinean Franc",
    "gtq" : "Guatemalan Quetzal",
    "hnl" : "Honduran Lempira",
    "hrk" : "Croatian Kuna",
    "htg" : "Haitian Gourde",
    "idr" : "Indonesian Rupiah",
    "iqd" : "Iraqi Dinar",
    "irr" : "Iranian Rial",
    "isk" : "Icelandic Krona",
    "jmd" : "Jamaican Dollar",
    "kes" : "Kenyan Shilling",
    "khr" : "Cambodian Riel",
    "kmf" : "Comorian Franc",
    "kzt" : "Kazakhstani Tenge",
    "lak" : "Laotian Kip",
    "lbp" : "Lebanese Pound",
    "lkr" : "Sri Lankan Rupee",
    "lsl" : "Lesotho Loti",
    "lyd" : "Libyan Dinar",
    "mad" : "Moroccan Dirham",
    "mdl" : "Moldovan Leu",
    "mga" : "Malagasy Ariary",
    "mkd" : "Macedonian Denar",
    "mmk" : "Myanmar Kyat",
    "mop" : "Macanese Pataca",
    "mro" : "Mauritanian Ouguiya",
    "mur" : "Mauritian Rupee",
    "mvr" : "Maldivian Rufiyaa",
    "mwk" : "Malawian Kwacha",
    "myr" : "Malaysian Ringgit",
    "nad" : "Namibian Dollar",
    "ngn" : "Nigerian Naira",
    "nio" : "Nicaraguan Córdoba",
    "npr" : "Nepalese Rupee",
    "nzd" : "New Zealand Dollar",
    "omr" : "Omani Rial",
    "pab" : "Panamanian Balboa",
    "pen" : "Peruvian Sol",
    "pgk" : "Papua New Guinean Kina",
    "php" : "Philippine Peso",
    "pkr" : "Pakistani Rupee",
    "pyg" : "Paraguayan Guarani",
    "qar" : "Qatari Rial",
    "ron" : "Romanian Leu",
    "rsd" : "Serbian Dinar",
    "rwf" : "Rwandan Franc",
    "scr" : "Seychellois Rupee",
    "sdg" : "Sudanese Pound",
    "sos" : "Somali Shilling",
    "std" : "São Tomé and Príncipe Dobra",
    "svc" : "Salvadoran Colón",
    "syp" : "Syrian Pound",
    "szl" : "Swazi Lilangeni",
    "tnd" : "Tunisian Dinar",
    "ttd" : "Trinidadian Dollar",
    "twd" : "Taiwan Dollar",
    "tzs" : "Tanzanian Shilling",
    "uah" : "Ukrainian Hryvnia",
    "ugx" : "Ugandan Shilling",
    "uyu" : "Uruguayan Peso",
    "uzs" : "Uzbekistani Som",
    "vef" : "Venezuelan Bolívar",
    "vnd" : "Vietnamese Dong",
    "vuv" : "Vanuatu Vatu",
    "xaf" : "Central African CFA Franc",
    "xcd" : "East Caribbean Dollar",
    "xof" : "West African CFA Franc",
    "xpf" : "CFP Franc",
    "yer" : "Yemeni Rial",
    "zmk" : "Zambian Kwacha",
    "byn" : "Belarusian Ruble",
    "mzn" : "Mozambican Metical",
    "azn" : "Azerbaijani Manat",
    "cnh" : "Offshore Chinese Yuan",
    "kgs" : "Kyrgyzstani Som",
    "tjs" : "Tajikistani Somoni",
    "rub" : "Russian Ruble",
    "aoa" : "Angolan Kwanza",
    "tmt" : "Turkmenistani Manat",
    "mnt" : "Mongolian Tugrik",
    "afn" : "Afghan Afghani",
    "zwl" : "Zimbabwean Dollar",
    "kyd" : "Cayman Islands Dollar"
};
